// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtTeumXvGLxjizSUNR17wGN6LnTvf9CTA',
    appId: '1:824629614680:web:5aebe2ae5d0499ebc9122d',
    messagingSenderId: '824629614680',
    projectId: 'credexa-de0fb',
    authDomain: 'credexa-de0fb.firebaseapp.com',
    storageBucket: 'credexa-de0fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC14bJZ8vt1ePzuUyz74f3eaMLNIHu7YbY',
    appId: '1:824629614680:android:06da15aca6bc2cb1c9122d',
    messagingSenderId: '824629614680',
    projectId: 'credexa-de0fb',
    storageBucket: 'credexa-de0fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_f9niWBwRGBFlL8ngAA67RXCM3fPQEwM',
    appId: '1:824629614680:ios:25644f524f91279bc9122d',
    messagingSenderId: '824629614680',
    projectId: 'credexa-de0fb',
    storageBucket: 'credexa-de0fb.firebasestorage.app',
    iosClientId: '824629614680-o95178rol2s07ss751s53tkto3fg49t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.credexaStemforchange',
  );
}
